In [1]:
import pandas as pd
import numpy as np

In [2]:
x=pd.read_csv(r"D:\work\imdb_anime.csv")

In [3]:
x

,Title,Genre,User Rating,Number of Votes,Runtime,Year,Summary,Stars,Certificate,Metascore,Gross,Episode,Episode Title
0,One Piece,"Animation, Action, Adventure",8.9,"187,689",24 min,(1999– ),Follows the adventures of Monkey D. Luffy and ...,"Mayumi Tanaka,Laurent Vernin,Akemi Okamura,Ton...",TV-14,NaN,187689,0,NaN
1,Teenage Mutant Ninja Turtles: Mutant Mayhem,"Animation, Action, Adventure",7.4,"28,895",99 min,(2023),The film follows the Turtle brothers as they w...,NaN,PG,74,28895,0,NaN
2,The Super Mario Bros. Movie,"Animation, Adventure, Comedy",7.1,"189,108",92 min,(2023),A plumber named Mario travels through an under...,NaN,PG,46,189108,0,NaN
3,Attack on Titan,"Animation, Action, Adventure",9.1,"434,457",24 min,(2013–2023),After his hometown is destroyed and his mother...,"Josh Grelle,Bryce Papenbrook,Yûki Kaji,Yui Ish...",TV-MA,NaN,434457,0,NaN
4,Jujutsu Kaisen,"Animation, Action, Adventure",8.5,"82,909",24 min,(2020– ),A boy swallows a cursed talisman - the finger ...,"Junya Enoki,Yûichi Nakamura,Adam McArthur,Yuma...",TV-MA,NaN,82909,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45712,Demon Slayer: Kimetsu no Yaiba,"Animation, Action, Adventure",7.3,"3,432",24 min,(2019– ),Tanjiro heads to his next location southeast; ...,NaN,TV-14,NaN,3432,1,Tsuzumi Mansion
45713,Demon Slayer: Kimetsu no Yaiba,"Animation, Action, Adventure",7.9,"3,309",24 min,(2019– ),Tanjiro gets separated from Zenitsu when he en...,NaN,TV-MA,NaN,3309,1,"The Boar Bares Its Fangs, Zenitsu Sleeps"
45714,One Piece,"Animation, Action, Adventure",9.4,"2,743",NaN,(1999– ),Carrot tells Sanji the news about Pedro. Germa...,"Mayumi Tanaka,Tom Henry,Masako Katsuki,Mami Ko...",TV-14,NaN,2743,1,Time for Farewell! Pudding's One Last Request!
45715,Marmalade Boy,"Animation, Comedy, Drama",NaN,NaN,24 min,(1994–2005),NaN,"Ogie Banks,Deborah Sale Butler,John DeMita,Ric...",Not Rated,NaN,NaN,1,Hijiri naru yoru (ivu nanoni hitori bocchi...)
45716,Cinderella Nine,"Animation, Drama, Sport",6.0,6,24 min,(2019– ),On her very first day at Satogahama Municipal ...,NaN,NaN,NaN,6,1,Play Ball!

In [4]:
x["Title"].unique

<bound method Series.unique of 0                                          One Piece
1        Teenage Mutant Ninja Turtles: Mutant Mayhem
2                        The Super Mario Bros. Movie
3                                    Attack on Titan
4                                     Jujutsu Kaisen
                            ...
45712                 Demon Slayer: Kimetsu no Yaiba
45713                 Demon Slayer: Kimetsu no Yaiba
45714                                      One Piece
45715                                  Marmalade Boy
45716                                Cinderella Nine
Name: Title, Length: 45717, dtype: object>

# 1. How many unique animes are there?

In [5]:
x["Title"].value_counts()

Doraemon                                             2758
Sazae-san                                            2397
Detective Conan                                      1005
Pokémon                                               990
One Piece                                             905
                                                     ...
Outburst Dreamer Boys                                   1
Shoot! Goal to the Future                               1
2112: The Birth of Doraemon                             1
Ghost Sweeper Mikami: The Great Paradise Battle!!       1
JoJo's Bizarre Adventure: Golden Wind                   1
Name: Title, Length: 9851, dtype: int64

# 2. Which anime has highest rating?

In [7]:
x["User Rating"].value_counts()

7.6            1270
7.5            1174
7.4            1171
7.2            1144
7.7            1142
               ...
1.7               2
1.8               2
2.1               2
2.5               1
User Rating       1
Name: User Rating, Length: 87, dtype: int64

In [8]:
x.replace({"User Rating":{"User Rating":0}},inplace=True)

In [9]:
x1=x.astype({"User Rating":float})

In [10]:
x1

,Title,Genre,User Rating,Number of Votes,Runtime,Year,Summary,Stars,Certificate,Metascore,Gross,Episode,Episode Title
0,One Piece,"Animation, Action, Adventure",8.9,"187,689",24 min,(1999– ),Follows the adventures of Monkey D. Luffy and ...,"Mayumi Tanaka,Laurent Vernin,Akemi Okamura,Ton...",TV-14,NaN,187689,0,NaN
1,Teenage Mutant Ninja Turtles: Mutant Mayhem,"Animation, Action, Adventure",7.4,"28,895",99 min,(2023),The film follows the Turtle brothers as they w...,NaN,PG,74,28895,0,NaN
2,The Super Mario Bros. Movie,"Animation, Adventure, Comedy",7.1,"189,108",92 min,(2023),A plumber named Mario travels through an under...,NaN,PG,46,189108,0,NaN
3,Attack on Titan,"Animation, Action, Adventure",9.1,"434,457",24 min,(2013–2023),After his hometown is destroyed and his mother...,"Josh Grelle,Bryce Papenbrook,Yûki Kaji,Yui Ish...",TV-MA,NaN,434457,0,NaN
4,Jujutsu Kaisen,"Animation, Action, Adventure",8.5,"82,909",24 min,(2020– ),A boy swallows a cursed talisman - the finger ...,"Junya Enoki,Yûichi Nakamura,Adam McArthur,Yuma...",TV-MA,NaN,82909,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45712,Demon Slayer: Kimetsu no Yaiba,"Animation, Action, Adventure",7.3,"3,432",24 min,(2019– ),Tanjiro heads to his next location southeast; ...,NaN,TV-14,NaN,3432,1,Tsuzumi Mansion
45713,Demon Slayer: Kimetsu no Yaiba,"Animation, Action, Adventure",7.9,"3,309",24 min,(2019– ),Tanjiro gets separated from Zenitsu when he en...,NaN,TV-MA,NaN,3309,1,"The Boar Bares Its Fangs, Zenitsu Sleeps"
45714,One Piece,"Animation, Action, Adventure",9.4,"2,743",NaN,(1999– ),Carrot tells Sanji the news about Pedro. Germa...,"Mayumi Tanaka,Tom Henry,Masako Katsuki,Mami Ko...",TV-14,NaN,2743,1,Time for Farewell! Pudding's One Last Request!
45715,Marmalade Boy,"Animation, Comedy, Drama",NaN,NaN,24 min,(1994–2005),NaN,"Ogie Banks,Deborah Sale Butler,John DeMita,Ric...",Not Rated,NaN,NaN,1,Hijiri naru yoru (ivu nanoni hitori bocchi...)
45716,Cinderella Nine,"Animation, Drama, Sport",6.0,6,24 min,(2019– ),On her very first day at Satogahama Municipal ...,NaN,NaN,NaN,6,1,Play Ball!

In [11]:
x1["User Rating"].max()

9.9

In [12]:
x1.loc[x1["User Rating"]==9.9]

,Title,Genre,User Rating,Number of Votes,Runtime,Year,Summary,Stars,Certificate,Metascore,Gross,Episode,Episode Title
13656,Idaten Jump,"Animation, Adventure, Comedy",9.9,11,20 min,(2005–2006),NaN,"Dorothy Elias-Fahn,Yuri Lowenthal,Michelle Ruf...",TV-PG,NaN,11,1,X City no monban
17874,Vinland Saga,"Animation, Action, Adventure",9.9,"13,663",24 min,(2019– ),"As the Imperial Council proceeds, Askeladd is ...","Mike Haimoto,Yûto Uemura,Naoya Uchida,David Wald",TV-MA,NaN,13663,1,End of The Prologue
22753,Attack on Titan,"Animation, Action, Adventure",9.9,"86,907",24 min,(2013–2023),As the battle between Eren and the warriors ra...,NaN,TV-MA,NaN,86907,1,Assault
34677,Hunter x Hunter,"Animation, Action, Adventure",9.9,"9,012",23 min,(2011–2014),Gon goes beyond his body limits to achieve mon...,NaN,TV-MA,NaN,9012,1,Anger × and × Light
39614,Legend of the Galactic Heroes,"Animation, Action, Drama",9.9,350,32 min,(1988–1997),"After extermination of the Terraist remnants, ...",NaN,TV-MA,NaN,350,1,Dream: To See It to the End
45689,Attack on Titan,"Animation, Action, Adventure",9.9,"109,163",24 min,(2013–2023),As Erwin's heroic charge buys Levi time to con...,NaN,TV-MA,NaN,109163,1,Hero

# 3. Which animes are having the ratings b/w 7 and 9?

In [13]:
x1.loc[x1["User Rating"]>7 & (x1["User Rating"]<9)]

,Title,Genre,User Rating,Number of Votes,Runtime,Year,Summary,Stars,Certificate,Metascore,Gross,Episode,Episode Title
0,One Piece,"Animation, Action, Adventure",8.9,"187,689",24 min,(1999– ),Follows the adventures of Monkey D. Luffy and ...,"Mayumi Tanaka,Laurent Vernin,Akemi Okamura,Ton...",TV-14,NaN,187689,0,NaN
1,Teenage Mutant Ninja Turtles: Mutant Mayhem,"Animation, Action, Adventure",7.4,"28,895",99 min,(2023),The film follows the Turtle brothers as they w...,NaN,PG,74,28895,0,NaN
2,The Super Mario Bros. Movie,"Animation, Adventure, Comedy",7.1,"189,108",92 min,(2023),A plumber named Mario travels through an under...,NaN,PG,46,189108,0,NaN
3,Attack on Titan,"Animation, Action, Adventure",9.1,"434,457",24 min,(2013–2023),After his hometown is destroyed and his mother...,"Josh Grelle,Bryce Papenbrook,Yûki Kaji,Yui Ish...",TV-MA,NaN,434457,0,NaN
4,Jujutsu Kaisen,"Animation, Action, Adventure",8.5,"82,909",24 min,(2020– ),A boy swallows a cursed talisman - the finger ...,"Junya Enoki,Yûichi Nakamura,Adam McArthur,Yuma...",TV-MA,NaN,82909,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45711,Demon Slayer: Kimetsu no Yaiba,"Animation, Action, Adventure",8.4,"3,375",24 min,(2019– ),With Tamayo coming to Nezuko's aid the battle ...,NaN,TV-MA,NaN,3375,1,Together Forever
45712,Demon Slayer: Kimetsu no Yaiba,"Animation, Action, Adventure",7.3,"3,432",24 min,(2019– ),Tanjiro heads to his next location southeast; ...,NaN,TV-14,NaN,3432,1,Tsuzumi Mansion
45713,Demon Slayer: Kimetsu no Yaiba,"Animation, Action, Adventure",7.9,"3,309",24 min,(2019– ),Tanjiro gets separated from Zenitsu when he en...,NaN,TV-MA,NaN,3309,1,"The Boar Bares Its Fangs, Zenitsu Sleeps"
45714,One Piece,"Animation, Action, Adventure",9.4,"2,743",NaN,(1999– ),Carrot tells Sanji the news about Pedro. Germa...,"Mayumi Tanaka,Tom Henry,Masako Katsuki,Mami Ko...",TV-14,NaN,2743,1,Time for Farewell! Pudding's One Last Request!
45716,Cinderella Nine,"Animation, Drama, Sport",6.0,6,24 min,(2019– ),On her very first day at Satogahama Municipal ...,NaN,NaN,NaN,6,1,Play Ball!

# 4.  Which anime has the highest and lowest runtime?

In [14]:
x1["Runtime"]=x1["Runtime"].str.replace(" min","")

In [15]:
x1["Runtime"]

0         24
1         99
2         92
3         24
4         24
        ...
45712     24
45713     24
45714    NaN
45715     24
45716     24
Name: Runtime, Length: 45717, dtype: object

In [20]:
x1=x1.astype({"Runtime":float})

In [17]:
x1.replace({"Runtime":{"Runtime":0}},inplace=True)

In [19]:
x1["Runtime"]=x1["Runtime"].str.replace(",","")

In [25]:
x1.loc[x1["Runtime"].max()]

Title                                                      Charlotte
Genre                                       Animation, Drama, Family
User Rating                                                      7.5
Number of Votes                                                7,486
Runtime                                                         24.0
Year                                                     (2015–2016)
Summary            The story takes place in an alternate reality ...
Stars              Kôki Uchiyama,Ayane Sakura,Momo Asakura,Takahi...
Certificate                                                    TV-PG
Metascore                                                        NaN
Gross                                                           7486
Episode                                                            0
Episode Title                                                    NaN
Name: 1271, dtype: object

In [26]:
x1.loc[x1["Runtime"].min()]

Title                    Teenage Mutant Ninja Turtles: Mutant Mayhem
Genre                                   Animation, Action, Adventure
User Rating                                                      7.4
Number of Votes                                               28,895
Runtime                                                         99.0
Year                                                          (2023)
Summary            The film follows the Turtle brothers as they w...
Stars                                                            NaN
Certificate                                                       PG
Metascore                                                 74
Gross                                                          28895
Episode                                                            0
Episode Title                                                    NaN
Name: 1, dtype: object

# 5. What is the runtime difference between one Piece and the super mario bros movie?

In [31]:
x1.loc[x1["Title"]=="One Piece",["Runtime"]]

       Runtime
0         24.0
841       24.0
13549     24.0
13550     25.0
13551     24.0
...        ...
45359      NaN
45373      NaN
45584      NaN
45649      NaN
45714      NaN

[905 rows x 1 columns]

In [32]:
x1.loc[x1["Title"]=="The Super Mario Bros. Movie",["Runtime"]]

     Runtime
2       92.0
843     92.0

In [38]:
x1=x1.astype({"Genre":str})

In [45]:
x1["Genre"].str.find("Action")

0        11
1        11
2        -1
3        11
4        11
         ..
45712    11
45713    11
45714    11
45715    -1
45716    -1
Name: Genre, Length: 45717, dtype: int64

# 9. Which anime has highest gross?

In [50]:
x1["Gross"]=x1["Gross"].str.replace("Gross","0")

In [51]:
x1=x1.astype({"Gross":float})

In [56]:
x1.loc[x1["Gross"]==1162284]

,Title,Genre,User Rating,Number of Votes,Runtime,Year,Summary,Stars,Certificate,Metascore,Gross,Episode,Episode Title
47,WALL·E,"Animation, Adventure, Family",8.4,"1,162,284",98.0,(2008),"In the distant future, a small waste-collectin...",NaN,G,95,1162284.0,0,NaN
888,WALL·E,"Animation, Adventure, Family",8.4,"1,162,284",98.0,(2008),"In the distant future, a small waste-collectin...",NaN,G,95,1162284.0,0,NaN

# 10. Which anime has least gross?

In [57]:
x1.loc[x1["Gross"].min()]

Title                                                      One Piece
Genre                                   Animation, Action, Adventure
User Rating                                                      8.9
Number of Votes                                              187,689
Runtime                                                         24.0
Year                                                        (1999– )
Summary            Follows the adventures of Monkey D. Luffy and ...
Stars              Mayumi Tanaka,Laurent Vernin,Akemi Okamura,Ton...
Certificate                                                    TV-14
Metascore                                                        NaN
Gross                                                       187689.0
Episode                                                            0
Episode Title                                                    NaN
Name: 0, dtype: object

# 11. How many animes belongs to PG certificate?

In [59]:
x1.loc[x1["Certificate"]=="PG"]

,Title,Genre,User Rating,Number of Votes,Runtime,Year,Summary,Stars,Certificate,Metascore,Gross,Episode,Episode Title
1,Teenage Mutant Ninja Turtles: Mutant Mayhem,"Animation, Action, Adventure",7.4,"28,895",99.0,(2023),The film follows the Turtle brothers as they w...,NaN,PG,74,28895.0,0,NaN
2,The Super Mario Bros. Movie,"Animation, Adventure, Comedy",7.1,"189,108",92.0,(2023),A plumber named Mario travels through an under...,NaN,PG,46,189108.0,0,NaN
7,Puss in Boots: The Last Wish,"Animation, Adventure, Comedy",7.8,"153,495",102.0,(2022),When Puss in Boots discovers that his passion ...,NaN,PG,73,153495.0,0,NaN
11,Coraline,"Animation, Drama, Family",7.7,"250,338",100.0,(2009),An adventurous 11-year-old girl finds another ...,NaN,PG,80,250338.0,0,NaN
17,Sing 2,"Animation, Adventure, Comedy",7.4,"78,880",110.0,(2021),Buster Moon and his friends must persuade recl...,NaN,PG,49,78880.0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41231,You're Under Arrest!,"Animation, Action, Comedy",NaN,NaN,24.0,(1996–2008),NaN,NaN,PG,NaN,NaN,1,Karokku Beibi
41232,You're Under Arrest!,"Animation, Action, Comedy",NaN,NaN,24.0,(1996–2008),NaN,NaN,PG,NaN,NaN,1,Aoi-chan Otoko ni Naru!?
41233,You're Under Arrest!,"Animation, Action, Comedy",NaN,NaN,24.0,(1996–2008),NaN,NaN,PG,NaN,NaN,1,Nikaido Yoriko wa Otoshigoro
41234,You're Under Arrest!,"Animation, Action, Comedy",NaN,NaN,24.0,(1996–2008),NaN,NaN,PG,NaN,NaN,1,Bichi Saido Ran
41235,You're Under Arrest!,"Animation, Action, Comedy",NaN,NaN,24.0,(1996–2008),NaN,NaN,PG,NaN,NaN,1,Tsuigeki! Reddo Fantomu

# 12. What is the avg number of votes?

In [64]:
x1["Number of Votes"]=x1["Number of Votes"].str.replace(",","")

In [66]:
x1.replace({"Number of Votes":{"Number of Votes":0}},inplace=True)

In [67]:
x1=x1.astype({"Number of Votes":float})

In [68]:
x1["Number of Votes"].mean()

2983.6828341796954